"""add user id field

Revision ID: 1175cc743514
Revises: c6c043679237
Create Date: 2025-05-04 23:05:45.356576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1175cc743514'
down_revision: Union[str, None] = 'c6c043679237'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'payments', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_column('payments', 'user_id')
    # ### end Alembic commands ###
