"""add promocode table

Revision ID: 284b66176cbb
Revises: bf0513b4aa0c
Create Date: 2025-05-21 11:36:34.259602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '284b66176cbb'
down_revision: Union[str, None] = 'bf0513b4aa0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promocode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('promocode', sa.String(), nullable=True),
    sa.Column('products', sa.String(), nullable=True),
    sa.Column('discount_type', sa.String(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('available', sa.Boolean(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('expired_on', sa.Date(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('promocode')
    # ### end Alembic commands ###
