"""remove table

Revision ID: 3597aef74790
Revises: d083e6b5809f
Create Date: 2025-04-21 17:12:15.240186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3597aef74790'
down_revision: Union[str, None] = 'd083e6b5809f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_cart_id', table_name='user_cart')
    op.drop_table('user_cart')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_cart',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cart_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cart_id'], ['user_cart.id'], name='user_cart_cart_id_fkey'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='user_cart_product_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_cart_pkey')
    )
    op.create_index('ix_user_cart_id', 'user_cart', ['id'], unique=False)
    # ### end Alembic commands ###
