"""Initial migration

Revision ID: 39536d4677d7
Revises: 622548e0efd9
Create Date: 2025-03-18 15:26:34.996922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39536d4677d7'
down_revision: Union[str, None] = '622548e0efd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('in_stock', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'in_stock')
    # ### end Alembic commands ###
