"""add page section

Revision ID: 3d936d113fb4
Revises: eeafcf71438b
Create Date: 2025-05-27 15:08:08.524098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d936d113fb4'
down_revision: Union[str, None] = 'eeafcf71438b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pagesection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_url', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pagesection')
    # ### end Alembic commands ###
