"""add address in Pyamnets

Revision ID: 4cd579be1682
Revises: e2f0b3d4d980
Create Date: 2025-04-29 12:23:52.462857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cd579be1682'
down_revision: Union[str, None] = 'e2f0b3d4d980'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('address', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'address')
    # ### end Alembic commands ###
