"""add ingredients field in product

Revision ID: 526ec5ff4000
Revises: dbce820cbe34
Create Date: 2025-05-29 11:52:11.386420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '526ec5ff4000'
down_revision: Union[str, None] = 'dbce820cbe34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('ingredients', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'ingredients')
    # ### end Alembic commands ###
