"""add promocode in payment

Revision ID: 53c5b58b62f3
Revises: e29cae041d79
Create Date: 2025-05-22 19:39:23.968685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53c5b58b62f3'
down_revision: Union[str, None] = 'e29cae041d79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('promocode', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'promocode')
    # ### end Alembic commands ###
