"""add field

Revision ID: 5590636ddd74
Revises: d15261350884
Create Date: 2025-05-29 11:54:17.169858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5590636ddd74'
down_revision: Union[str, None] = 'd15261350884'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('ingredients', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'ingredients')
    # ### end Alembic commands ###
