"""add phone in payments

Revision ID: 586885e691c2
Revises: 4cd579be1682
Create Date: 2025-04-29 12:36:07.412617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '586885e691c2'
down_revision: Union[str, None] = '4cd579be1682'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('customer_phone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'customer_phone')
    # ### end Alembic commands ###
