"""add cart

Revision ID: 5cb7ff663cc6
Revises: 09ee4b22ab5b
Create Date: 2025-04-21 18:14:59.843192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cb7ff663cc6'
down_revision: Union[str, None] = '09ee4b22ab5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_cart_association', sa.Column('quantity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_cart_association', 'quantity')
    # ### end Alembic commands ###
