"""change in rating review

Revision ID: 66a67164bc60
Revises: 605549b023c5
Create Date: 2025-05-19 13:43:38.291304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66a67164bc60'
down_revision: Union[str, None] = '605549b023c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('rating', sa.Float(), nullable=True))
    op.add_column('rating_review', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'rating_review', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rating_review', type_='foreignkey')
    op.drop_column('rating_review', 'user_id')
    op.drop_column('products', 'rating')
    # ### end Alembic commands ###
