"""add new table and update table

Revision ID: 9da0a3b3618a
Revises: 586885e691c2
Create Date: 2025-05-04 17:25:24.962130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9da0a3b3618a'
down_revision: Union[str, None] = '586885e691c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_webhook',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('payments', sa.Column('orders', sa.String(), nullable=True))
    op.add_column('payments', sa.Column('payment_method', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'payment_method')
    op.drop_column('payments', 'orders')
    op.drop_table('payment_webhook')
    # ### end Alembic commands ###
