"""add created on

Revision ID: bf0513b4aa0c
Revises: 66a67164bc60
Create Date: 2025-05-19 15:07:36.905295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf0513b4aa0c'
down_revision: Union[str, None] = '66a67164bc60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rating_review', sa.Column('added_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rating_review', 'added_on')
    # ### end Alembic commands ###
