"""remove field

Revision ID: d15261350884
Revises: 526ec5ff4000
Create Date: 2025-05-29 11:53:46.014032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd15261350884'
down_revision: Union[str, None] = '526ec5ff4000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'ingredients')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('ingredients', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
