"""add cancellation

Revision ID: dbce820cbe34
Revises: 3d936d113fb4
Create Date: 2025-05-28 15:20:02.702813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbce820cbe34'
down_revision: Union[str, None] = '3d936d113fb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('cancellation_reason', sa.Text(), nullable=True))
    op.add_column('orders', sa.Column('cancellation_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'cancellation_date')
    op.drop_column('orders', 'cancellation_reason')
    # ### end Alembic commands ###
