"""add pincode

Revision ID: dfd7f9eac756
Revises: 5cb7ff663cc6
Create Date: 2025-04-21 19:18:04.705713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfd7f9eac756'
down_revision: Union[str, None] = '5cb7ff663cc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pincode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pincode', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pincode_id'), 'pincode', ['id'], unique=False)
    op.create_index(op.f('ix_pincode_pincode'), 'pincode', ['pincode'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pincode_pincode'), table_name='pincode')
    op.drop_index(op.f('ix_pincode_id'), table_name='pincode')
    op.drop_table('pincode')
    # ### end Alembic commands ###
