"""add promocode table

Revision ID: e29cae041d79
Revises: 284b66176cbb
Create Date: 2025-05-21 12:01:00.077459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e29cae041d79'
down_revision: Union[str, None] = '284b66176cbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promocode', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'promocode', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'promocode', type_='foreignkey')
    op.drop_column('promocode', 'created_by')
    # ### end Alembic commands ###
