"""add product in Payment

Revision ID: e2f0b3d4d980
Revises: b22ebdd48c29
Create Date: 2025-04-29 12:16:19.035749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2f0b3d4d980'
down_revision: Union[str, None] = 'b22ebdd48c29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('products', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'products')
    # ### end Alembic commands ###
